# -*- coding: utf8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.dialects.mysql import *

metadata = MetaData()


auth_group =  Table('auth_group', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=80), primary_key=False, nullable=False),
    
    
    )
Index(u'name', auth_group.c.name, unique=True)


auth_group_permissions =  Table('auth_group_permissions', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'group_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'permission_id', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'group_id'], [u'forum.auth_group.id'], name=u'group_id_refs_id_3cea63fe'),
            ForeignKeyConstraint([u'permission_id'], [u'forum.auth_permission.id'], name=u'permission_id_refs_id_a7792de1'),
    
    )
Index(u'group_id', auth_group_permissions.c.group_id, auth_group_permissions.c.permission_id, unique=True)
Index(u'permission_id_refs_id_a7792de1', auth_group_permissions.c.permission_id, unique=False)


auth_permission =  Table('auth_permission', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=50), primary_key=False, nullable=False),
            Column(u'content_type_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'codename', VARCHAR(length=100), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'content_type_id'], [u'forum.django_content_type.id'], name=u'content_type_id_refs_id_728de91f'),
    
    )
Index(u'content_type_id', auth_permission.c.content_type_id, auth_permission.c.codename, unique=True)


auth_user =  Table('auth_user', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'username', VARCHAR(length=30), primary_key=False, nullable=False),
            Column(u'first_name', VARCHAR(length=30), primary_key=False, nullable=False),
            Column(u'last_name', VARCHAR(length=30), primary_key=False, nullable=False),
            Column(u'email', VARCHAR(length=75), primary_key=False, nullable=False),
            Column(u'password', VARCHAR(length=128), primary_key=False, nullable=False),
            Column(u'is_staff', Integer(), primary_key=False, nullable=False),
            Column(u'is_active', Integer(), primary_key=False, nullable=False),
            Column(u'is_superuser', Integer(), primary_key=False, nullable=False),
            Column(u'last_login', DATETIME(), primary_key=False, nullable=False),
            Column(u'date_joined', DATETIME(), primary_key=False, nullable=False),
    
    
    )
Index(u'username', auth_user.c.username, unique=True)


auth_user_groups =  Table('auth_user_groups', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'user_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'group_id', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'group_id'], [u'forum.auth_group.id'], name=u'group_id_refs_id_f0ee9890'),
            ForeignKeyConstraint([u'user_id'], [u'forum.auth_user.id'], name=u'user_id_refs_id_831107f1'),
    
    )
Index(u'group_id_refs_id_f0ee9890', auth_user_groups.c.group_id, unique=False)
Index(u'user_id', auth_user_groups.c.user_id, auth_user_groups.c.group_id, unique=True)


auth_user_user_permissions =  Table('auth_user_user_permissions', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'user_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'permission_id', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'permission_id'], [u'forum.auth_permission.id'], name=u'permission_id_refs_id_67e79cb'),
            ForeignKeyConstraint([u'user_id'], [u'forum.auth_user.id'], name=u'user_id_refs_id_f2045483'),
    
    )
Index(u'user_id', auth_user_user_permissions.c.user_id, auth_user_user_permissions.c.permission_id, unique=True)
Index(u'permission_id_refs_id_67e79cb', auth_user_user_permissions.c.permission_id, unique=False)


django_content_type =  Table('django_content_type', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'name', VARCHAR(length=100), primary_key=False, nullable=False),
            Column(u'app_label', VARCHAR(length=100), primary_key=False, nullable=False),
            Column(u'model', VARCHAR(length=100), primary_key=False, nullable=False),
    
    
    )
Index(u'app_label', django_content_type.c.app_label, django_content_type.c.model, unique=True)


django_session =  Table('django_session', metadata,
    Column(u'session_key', VARCHAR(length=40), primary_key=True, nullable=False),
            Column(u'session_data', String(), primary_key=False, nullable=False),
            Column(u'expire_date', DATETIME(), primary_key=False, nullable=False),
    
    
    )


django_site =  Table('django_site', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'domain', VARCHAR(length=100), primary_key=False, nullable=False),
            Column(u'name', VARCHAR(length=50), primary_key=False, nullable=False),
    
    
    )


v0_post =  Table('v0_post', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'title', VARCHAR(length=120), primary_key=False, nullable=False),
            Column(u'body', VARCHAR(length=8000), primary_key=False, nullable=False),
            Column(u'user_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'date', DATETIME(), primary_key=False, nullable=False),
            Column(u'comment', Integer(), primary_key=False, nullable=False),
            Column(u'edited', Integer(), primary_key=False, nullable=False),
            Column(u'parent_id', INTEGER(), primary_key=False),
            Column(u'identifier', INTEGER(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'user_id'], [u'forum.auth_user.id'], name=u'user_id_refs_id_b1d21950'),
            ForeignKeyConstraint([u'parent_id'], [u'forum.v0_post.id'], name=u'parent_id_refs_id_57de2a93'),
    
    )
Index(u'parent_id_refs_id_57de2a93', v0_post.c.parent_id, unique=False)
Index(u'user_id_refs_id_b1d21950', v0_post.c.user_id, unique=False)


v0_relvote =  Table('v0_relvote', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'user_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'post_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'parent_post_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'date_expire', DATETIME(), primary_key=False, nullable=False),
            Column(u'_next_id', INTEGER(), primary_key=False),
    ForeignKeyConstraint([u'post_id'], [u'forum.v0_post.id'], name=u'post_id_refs_id_5e638edd'),
            ForeignKeyConstraint([u'_next_id'], [u'forum.v0_relvote.id'], name=u'_next_id_refs_id_db5d050d'),
            ForeignKeyConstraint([u'user_id'], [u'forum.auth_user.id'], name=u'user_id_refs_id_ea911540'),
            ForeignKeyConstraint([u'parent_post_id'], [u'forum.v0_post.id'], name=u'parent_post_id_refs_id_5e638edd'),
    
    )
Index(u'_next_id_refs_id_db5d050d', v0_relvote.c._next_id, unique=False)
Index(u'post_id_refs_id_5e638edd', v0_relvote.c.post_id, unique=False)
Index(u'user_id_refs_id_ea911540', v0_relvote.c.user_id, unique=False)
Index(u'parent_post_id_refs_id_5e638edd', v0_relvote.c.parent_post_id, unique=False)


v0_revision =  Table('v0_revision', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'post_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'date_stored', DATETIME(), primary_key=False, nullable=False),
            Column(u'body', VARCHAR(length=8000), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'post_id'], [u'forum.v0_post.id'], name=u'post_id_refs_id_1dcfc91e'),
    
    )
Index(u'post_id_refs_id_1dcfc91e', v0_revision.c.post_id, unique=False)


v0_userprofile =  Table('v0_userprofile', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'user_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'authd', Integer(), primary_key=False, nullable=False),
    ForeignKeyConstraint([u'user_id'], [u'forum.auth_user.id'], name=u'user_id_refs_id_952250b'),
    
    )
Index(u'user_id', v0_userprofile.c.user_id, unique=True)


v0_vote =  Table('v0_vote', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'user_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'post_id', INTEGER(), primary_key=False, nullable=False),
            Column(u'parent_post_id', INTEGER(), primary_key=False),
    ForeignKeyConstraint([u'post_id'], [u'forum.v0_post.id'], name=u'post_id_refs_id_99232855'),
            ForeignKeyConstraint([u'user_id'], [u'forum.auth_user.id'], name=u'user_id_refs_id_5a6f2f72'),
            ForeignKeyConstraint([u'parent_post_id'], [u'forum.v0_post.id'], name=u'parent_post_id_refs_id_99232855'),
    
    )
Index(u'post_id_refs_id_99232855', v0_vote.c.post_id, unique=False)
Index(u'parent_post_id_refs_id_99232855', v0_vote.c.parent_post_id, unique=False)
Index(u'user_id_refs_id_5a6f2f72', v0_vote.c.user_id, unique=False)

